### ISSUE TITLE
Add NCT: Toucan Protocol: Nature Carbon Tonne

### ISSUE THREAD

**Issue by aspiers** [celo-org/celo-token-list#10]
Please add NCT at 0x02De4766C272abc10Bc88c220D214A26960a7e92:

- https://celoscan.io/token/0x02de4766c272abc10bc88c220d214a26960a7e92
- https://explorer.celo.org/token/0x02De4766C272abc10Bc88c220D214A26960a7e92/token-transfers

Thanks!

**Comment by Jesse-Sawa** [comment]
Hi @aspiers can you send the logo URI?

**Comment by aspiers** [comment]
Sure @Jesse-Sawa, is https://toucan.earth/img/logo-sm.svg what you are looking for?

**Comment by kargakis** [comment]
Or maybe the NCT logo?
Bright background:
![NCT-128px-bright](https://user-images.githubusercontent.com/3900799/184530757-3b3b6bd1-1a13-456d-9d6b-531bdfdaae4b.svg)
Dark background:
![NCT-128px-dark](https://user-images.githubusercontent.com/3900799/184530759-0942cdf8-6f2b-43c9-8c5e-dcefe7ac4adf.svg)

**Comment by aspiers** [comment]
Doh sorry - of course, it should be the NCT logo not the Toucan one :laughing: 

But we need to provide a URI permalink.  Here is a link to one NCT logo:

https://toucan.earth/img/icons/nct.svg

but I'm not sure whether bright or dark background is needed?

**Comment by Jesse-Sawa** [comment]
Okay, how does this look? 

    {
      "name": "Toucan",
      "address": "0x02de4766c272abc10bc88c220d214a26960a7e92",
      "symbol": "NCT",
      "decimals": 18,
      "chainId": 42220,
      "logoURI": "https://toucan.earth/img/icons/nct.svg"
    },

**Comment by Jesse-Sawa** [comment]
> Or maybe the NCT logo? Bright background: ![NCT-128px-bright](https://user-images.githubusercontent.com/3900799/184530757-3b3b6bd1-1a13-456d-9d6b-531bdfdaae4b.svg) Dark background: ![NCT-128px-dark](https://user-images.githubusercontent.com/3900799/184530759-0942cdf8-6f2b-43c9-8c5e-dcefe7ac4adf.svg)

These both look the same to me. The image url we specify here is at your discretion although it must be one that will not likely not change it the near future

**Comment by kargakis** [comment]
We don't plan to change the logo anytime soon so it should be fine.

> Okay, how does this look?

I think only the name should probably be updated to something like "Nature Carbon Tonne" or "Toucan Protocol: Nature Carbon Tonne"? @aspiers thoughts?

**Comment by Jesse-Sawa** [comment]
I just created the PR, just need a final say.

**Comment by aspiers** [comment]
Will be closed by #11.

**Comment by aspiers** [comment]
Looks good, please proceed!
