### ISSUE TITLE
Add {ATLASX}: {AtlasX Carbon Credits}

### ISSUE THREAD

**Issue by munivenkateswarluk** [celo-org/celo-token-list#18]
{
      "name": "AtlasX Carbon Credits",
      "address": "0xc3377Ea71F1dc8e55Ba360724eff2d7aD62a8670",
      "symbol": "ATLASX",
      "decimals": 18,
      "chainId": 42220,
      "logoURI": "https://myterrablobs.blob.core.windows.net/public/token-icon.png"
    }

**Comment by nicolasbrugneaux** [comment]
Hello,  as I'm ramping up on this repository, is this still necessary?

**Comment by nicolasbrugneaux** [comment]
For future reference here's the tracker screenshot
https://celoscan.io/token/0xC16B81Af351BA9e64C1a069E3Ab18c244A1E3049

![Screenshot 2023-10-30 at 14 21 38](https://github.com/celo-org/celo-token-list/assets/3650621/8fa5df1a-69f2-44d9-af0a-82de33debbf3)

**Comment by nicolasbrugneaux** [comment]
For future reference here's the tracker screenshot
https://celoscan.io/token/0xC16B81Af351BA9e64C1a069E3Ab18c244A1E3049

![Screenshot 2023-10-30 at 14 23 01](https://github.com/celo-org/celo-token-list/assets/3650621/3090f760-2f1c-49e3-b148-03dc1ed70703)
