### ISSUE TITLE
Add {CRV}: {Curve DAO Token}

### ISSUE THREAD

**Issue by amitchu** [celo-org/celo-token-list#21]
{
      "name": "Curve DAO Token",
      "address": "0x173fd7434B8B50dF08e3298f173487ebDB35FD14",
      "symbol": "CRV",
      "decimals": 18,
      "chainId": 42220,
      "logoURI": "https://raw.githubusercontent.com/curvefi/curve-assets/main/branding/logo.svg"
    }

**Comment by 0xarthurxyz** [comment]
Here is the token tracker page on celoscan: https://celoscan.io/token/0x173fd7434b8b50df08e3298f173487ebdb35fd14

<img width="1396" alt="image" src="https://github.com/celo-org/celo-token-list/assets/46296830/9d188a05-d131-4d12-923c-d6dcee6db4c4">

**Comment by nicolasbrugneaux** [comment]
Hello, as I'm ramping up on this repository, is this still necessary?
