### ISSUE TITLE
Add axelar bridged WBTC and wormhole/portal bridged WBTC

### ISSUE THREAD

**Issue by 0lektronisch** [celo-org/celo-token-list#23]
recently WBTC has been bridged, 1. via wormhole and 2. via axelar to Celo, for the first time.
They were used to create a ~ 5M $ pool on UniswapV3
https://info.uniswap.org/#/celo/pools/0xa373c25c61fe6659a575b6d40975182f2f1fb919

this was part of the proposal #91
https://celo.stake.id/#/proposal/91

axlWBTC = 0x1a35EE4640b0A3B87705B0A4B45D227Ba60Ca2ad

WBTC (wormhole) = 0xd71Ffd0940c920786eC4DbB5A12306669b5b81EF

Problem is, both appear as unknown token on uniswap and probably elsewhere.
Also a token Icon would be needed for both. Here the standard WBTC icon with an indicator which bridge was used would be preferred.

**Comment by Jesse-Sawa** [comment]
Hey @0lektronisch! Could you provide the following but for axlWBTC and wbtc wormhole. 

**Example**
{
      "name": "Staked Celo",
      "address": "0xC668583dcbDc9ae6FA3CE46462758188adfdfC24",
      "symbol": "stCelo",
      "decimals": 18,
      "chainId": 42220,
      "logoURI": "https://raw.githubusercontent.com/jesse-sawa/celo-token-list/master/assets/token-stcelo.svg"
    }
    
    
Once I have this, i'll add them to the token list

**Comment by 0lektronisch** [comment]
{

Hey @Jesse-Sawa here the information so far... i am still struggling creating icons for both.
Does they have to be ind .svg ??

name": "axelar bridged wrapped Bitcoin",
"address": "0x1a35EE4640b0A3B87705B0A4B45D227Ba60Ca2ad",
"symbol": "axlWBTC",
"decimals": 18,
"chainId": 42220,
"logoURI": ""

"name": "wormhole bridged wrapped Bitcoin",
"address": "0xd71Ffd0940c920786eC4DbB5A12306669b5b81EF",
"symbol": "WBTC",
"decimals": 18,
"chainId": 42220,
"logoURI": ""
}

**Comment by 0lektronisch** [comment]
@Jesse-Sawa 
just edited the form above. it now includes icon images in png format.
Does that work and makes sense?

**Comment by 0lektronisch** [comment]
@Jesse-Sawa
Is the information i provided enough? Is there anything i can help here?

**Comment by Jesse-Sawa** [comment]
@0lektronisch looks good, will create the PR now

**Comment by Jesse-Sawa** [comment]
Hi @0lektronisch. For the sake of maintaining consistency, please use the official logoURI supplied by both Axelar & Wormhole. I understand this is the first time the token has been bridged although, I believe both these groups have a process for the generating the token icons. 

Also, the link should be hosted by the respective organizations - alternatively we can host it in the assets directory

**Comment by 0lektronisch** [comment]
@Jesse-Sawa 
here are the new icon files.
1. axelar bridged WBTC: https://github.com/0lektronisch/icons/blob/main/axlWBTC.svg
2. wormhole bridged WBTC: https://github.com/0lektronisch/icons/blob/main/WBTCwh.png

they are according to their icon creation guidlines.

axelar provided me with the icon file they used for another chain.
wormhole uses png format and icons are 120x120px

**Comment by Jesse-Sawa** [comment]
Wormhole and Axelar Wrapped Bitcoin was added
