### ISSUE TITLE
Add USDGLO: Glo Dollar

### ISSUE THREAD

**Issue by Alex2050** [celo-org/celo-token-list#37]
{
      "name": "Glo Dollar",
      "address": "0x4f604735c1cf31399c6e711d5962b2b3e0225ad3",
      "symbol": "USDGLO",
      "decimals": 18,
      "chainId": 42220,
      "logoURI": "https://github.com/celo-org/celo-token-list/assets/13286383/660e3682-c9b9-4b91-b035-12f8c1b23a0a"

    }

**Comment by Jesse-Sawa** [comment]
Complete

**Comment by Alex2050** [comment]
We need a hosted image link of the logo from Glo Dollar team.

**Comment by gglucass** [comment]
Hi @Alex2050 - does https://app.glodollar.org/glo-logo.svg work?

**Comment by Alex2050** [comment]
Yes, updated.
