### ISSUE TITLE
Add USDGLO: Glo Dollar

### ISSUE THREAD

**Issue by gglucass** [celo-org/celo-token-list#40]
{
      "name": "Glo Dollar",
      "address": "0x4f604735c1cf31399c6e711d5962b2b3e0225ad3",
      "symbol": "USDGLO",
      "decimals": 18,
      "chainId": 42220,
      "logoURI": "https://i.imgur.com/k5ug2KE.png"
    }

**Comment by Jesse-Sawa** [comment]
Glo Dollar has already been added to the celo token list
