### ISSUE TITLE
Add agEUR: agEUR

### ISSUE THREAD

**Issue by amitchuapf** [celo-org/celo-token-list#42]
{
      "name": "agEUR",
      "address": "0xC16B81Af351BA9e64C1a069E3Ab18c244A1E3049",
      "symbol": "agEUR",
      "decimals": 18,
      "chainId": 42220,
      "logoURI": "https://github.com/AngleProtocol/angle-assets/blob/main/0_tokens/agEUR/cross-chain/agEUR-celo.svg"
    }

**Comment by nicolasbrugneaux** [comment]
For future reference here's the tracker screenshot
https://celoscan.io/token/0xC16B81Af351BA9e64C1a069E3Ab18c244A1E3049

![Screenshot 2023-10-30 at 14 21 38](https://github.com/celo-org/celo-token-list/assets/3650621/6e40c0de-2621-43ad-aebb-bad52e2f5237)
