### ISSUE TITLE
Add EURC: EURC (Wormhole)

### ISSUE THREAD

**Issue by amitchuapf** [celo-org/celo-token-list#44]
{
      "name": "EURC (Wormhole)",
      "address": "0xBddC3554269053544bE0d6d027a73271225E9859",
      "symbol": "EURC",
      "decimals": 6,
      "chainId": 42220,
      "logoURI": "https://raw.githubusercontent.com/wormhole-foundation/wormhole-token-list/main/assets/EURC_wh.png"
    }

**Comment by aaronmgdr** [comment]
Im not seeing this address on  https://github.com/wormhole-foundation/wormhole-token-list/blob/main/content/by_dest.csv

**Comment by amitchuapf** [comment]
Hi Aaron!

Thanks for taking a look at this. This is verified via Portal's token
origin verifier page. Attaching a screenshot for reference!

https://www.portalbridge.com/#/token-origin-verifier

**Comment by amitchuapf** [comment]
Hi,

Just following up on this to see if there's anything I can help provide to
approve this issue?

Thanks,

**Comment by aaronmgdr** [comment]
sorry it slipped thru thanks for following up

**Comment by aaronmgdr** [comment]
could you turn this into a PR?

**Comment by amitchuapf** [comment]
Hi Aaron,

Please see the PR here -

https://github.com/celo-org/celo-token-list/pull/45
