### ISSUE TITLE
Broken format, missing comma

### ISSUE THREAD

**Issue by 0xyijing** [celo-org/celo-token-list#51]
a comma is missing before 
{
      "name": "USD Coin",
      "address": "0xcebA9300f2b948710d2653dD7B07f33A8B32118C",
      "symbol": "USDC",
      "decimals": 6,
      "chainId": 42220,
      "logoURI": "https://raw.githubusercontent.com/compound-finance/token-list/master/assets/asset_USDC.svg"
}

**Comment by Dalcor** [comment]
I've created PR few days ago, but no approval so far

https://github.com/celo-org/celo-token-list/pulls

**Comment by shazarre** [comment]
@0xyijing thanks for creating the issue, @Dalcor thanks for submitting the PR, I've just merged it.
