### ISSUE TITLE
Maintain a tokenlist by chainId

### ISSUE THREAD

**Issue by ashachaf** [celo-org/celo-token-list#64]
Current implementation of the tokenlist includes tokens from both chainId 42220 and 44787.

Please split the list into two different lists, one for each chainId.
This will maintain tokenlist best practice structure where each list is dedicated for a dedicated chainId.

**Comment by sodofi** [comment]
@aaronmgdr if we change celo.tokenlist.json it can affect all the user calling the list as it is.

Do you have a preference here for which option we should do?

1. Celo.tokenlist.json stays as is and we make two new jsons called 'celo.mainnet.tokenlist.json' and 'celo.testnet.tokenlist.json' with the separate lists. This will create three token lists in total. However, this will mean we have two places where we will need to update.

2. Edit celo.tokenlist.json to only include mainnet tokens. Create a new celo.testnet.tokenlist.json with the testnet tokens. This will create two token lists in total. This will only affect users who are calling testnet token and hopefully minimal changes to mainnet token callers.

3. Don't make any changes and keep as is.

**Comment by nicolasbrugneaux** [comment]
I'm not entirely sure what the benefits of splitting the list is? Filtering values programmatically by chainId is easy enough and the list isn't big at all, so download size doesn't matter here. I'm strongly in favour of option 3

**Comment by aaronmgdr** [comment]
2. sound good to me

**Comment by aaronmgdr** [comment]
close by #67
