### ISSUE TITLE
Add cRecy: cRecy

### ISSUE THREAD

**Issue by biadebeatriz** [celo-org/celo-token-list#9]
![cRecy](https://user-images.githubusercontent.com/39596878/181092323-a95f3ab5-ef70-4103-9530-0bb1e2c52562.png)
Address: 0x34C11A932853Ae24E845Ad4B633E3cEf91afE583

**Comment by Jesse-Sawa** [comment]
Hi @biadebeatriz, would you provide the name of the token (cRECY is the ticker) as well as a link to the logo as opposed to the file?

**Comment by cryphtophil** [comment]
Hi @Jesse-Sawa !

The name of the token and the ticker are the same.

https://drive.google.com/file/d/16wiMAU8U8umDuwfNg7RnvqNe7DTxRYS2/view?usp=drivesdk

Thanks!🙏🏼
